import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import "./globals.css";

import { I18nProvider, ReactQueryProvider, ThemeProvider } from "@/core/providers";
import { getCurrentUser } from '@/features/user';
import { Navbar } from '@/widgets/navbar';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getCurrentUser();

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider>
          <I18nProvider>
            <ReactQueryProvider>
              <div className="flex min-h-screen flex-col">
                <Navbar user={user} />
                <main className="flex-1">{children}</main>
              </div>
            </ReactQueryProvider>
          </I18nProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
